order:
  billing:
    name: Joe Adams
  fulfillments:
    - customer:
        contact:
          phone: "9876556789"
        person:
          name: Joe Adams
      id: F1
      stops:
        - location:
            gps: "13.008935, 77.644408"
          type: START
        - location:
            gps: "12.971186, 77.586812"
          type: END
      vehicle:
        category: AUTO_RICKSHAW
        variant: AUTO_RICKSHAW
        energy_type: CNG
  items:
    - id: I1
  payments:
    - collected_by: BPP
      id: PA1
      params:
        bank_account_number: xxxxxxxxxxxxxx
        bank_code: XXXXXXXX
        virtual_payment_address: 9988199772@okicic
      status: NOT-PAID
      tags:
        - descriptor:
            code: BUYER_FINDER_FEES
          display: false
          list:
            - descriptor:
                code: BUYER_FINDER_FEES_PERCENTAGE
              value: "1"
        - descriptor:
            code: SETTLEMENT_TERMS
          display: false
          list:
            - descriptor:
                code: SETTLEMENT_WINDOW
              value: PT60M
            - descriptor:
                code: SETTLEMENT_BASIS
              value: DELIVERY
            - descriptor:
                code: SETTLEMENT_TYPE
              value: UPI
            - descriptor:
                code: MANDATORY_ARBITRATION
              value: "true"
            - descriptor:
                code: COURT_JURISDICTION
              value: New Delhi
            - descriptor:
                code: DELAY_INTEREST
              value: "5"
            - descriptor:
                code: STATIC_TERMS
              value: https://example-test-bap.com/static-terms.txt
            - descriptor:
                code: SETTLEMENT_AMOUNT
              value: "1.46"
      type: ON-FULFILLMENT
  provider:
    id: P1
