save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  order_id: "$.message.order.id"
  provider_id: "$.message.order.provider.id"
  loan_status: "$.message.order.fulfillments[0].state.descriptor.code"
  quote_id: "$.message.order.quote.id"
  quote: "$.message.order.quote"  
  form_id: "$.message.order.items[0].xinput.form.id"
