order:
  provider:
    id: PROVIDER_ID

  items:
    - id: CHILD_ITEM_ID_LOAN_1
      parent_item_id: ITEM_ID_PERSONAL_LOAN_2
      xinput:
        form:
          id: F04
        form_response:
          status: SUCCESS
          submission_id: F04_SUBMISSION_ID

  payments:
    - type: ON_FULFILLMENT
      id: LOAN_DISBURSMENT_ID
      status: NOT-PAID
      collected_by: CONSUMER
      params:
        bank_account_number: XXXXXXXX
        bank_code: XXXXXXXX
      time:
        label: LOAN_DISBURSMENT
      tags:
        - descriptor:
            name: Account Details
            code: ACCOUNT_DETAILS
          list:
            - descriptor:
                code: ACCOUNT_TYPE
                name: Account Type
              value: SAVINGS
            - descriptor:
                code: ACCOUNT_HOLDER_NAME
                name: Account Holder Name
              value: John Doe

  tags:
    - display: false
      descriptor:
        name: BAP Terms of Engagement
        code: BAP_TERMS
      list:
        - descriptor:
            code: STATIC_TERMS
          value: https://bap.credit.becknprotocol.io/working-capital/loans/working-capital
        - descriptor:
            code: OFFLINE_CONTRACT
          value: "true"
