save-data:
  latest_issue_payload: $.message.issue
  last_action: $.context.action
  issue_action : $.message.issue.actions[*]
  issue_resolution: $.message.issue.resolutions[*]
  last_actions_id: $.message.issue.actions[*]