message:
  order:
    id: "O1"
    status: "ACTIVE"

    items:
      - id: "I1"
        descriptor:
          name: "Single Journey Ticket"
          code: "SJT"
          images:
            - url: "https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png"
              size_type: "xs"
        fulfillment_ids: ["F1", "F5", "F6"]
        price:
          currency: "INR"
          value: "35"
        quantity:
          selected:
            count: 2
        time:
          label: "Validity"
          duration: "P2D"
          timestamp: "2021-03-23T11:01:40.065Z"

    provider:
      id: "P1"
      descriptor:
        name: "Delhi Transport Corporation"
        images:
          - url: "https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png"
            size_type: "xs"

    fulfillments:
      - id: "F1"
        type: "TRIP"
        stops:
          - type: "START"
            location:
              descriptor:
                name: "kashmere gate"
                code: "KASHMERE_GATE"
              gps: "28.666576, 77.233332"
            id: "1"
          - type: "INTERMEDIATE_STOP"
            instructions:
              name: "Stop 1"
            location:
              descriptor:
                name: "Indira Gandhi Technical Unviversity"
                code: "INDIRA_GANDHI_TECHNICAL_UNIV"
              gps: "28.624097, 77.204991"
            id: "2"
            parent_stop_id: "1"
          - type: "INTERMEDIATE_STOP"
            instructions:
              name: "Stop 2"
            location:
              descriptor:
                name: "Yamuna Bazar"
                code: "YAMUNA_BAZAR"
              gps: "28.625972,77.209917"
            id: "3"
            parent_stop_id: "2"
          - type: "INTERMEDIATE_STOP"
            instructions:
              name: "Stop 3"
            location:
              descriptor:
                name: "dhaula kuan"
                code: "DHAULA_KUAN"
              gps: "28.610972,77.201717"
            id: "4"
            parent_stop_id: "3"
          - type: "INTERMEDIATE_STOP"
            instructions:
              name: "Stop 4"
            location:
              descriptor:
                name: "gpo"
                code: "GPO"
              gps: "28.623097,77.209917"
            id: "5"
            parent_stop_id: "4"
          - type: "END"
            location:
              descriptor:
                name: "Greater Kailash"
                code: "GREATER_KAILASH"
              gps: "28.548230, 77.238039"
            id: "6"
            parent_stop_id: "5"
        vehicle:
          category: "BUS"
        state:
          descriptor:
            code: "INACTIVE"
        tags:
          - descriptor:
              code: "ROUTE_INFO"
            list:
              - descriptor:
                  code: "ROUTE_ID"
                value: "242"
              - descriptor:
                  code: "ROUTE_DIRECTION"
                value: "UP"

      - id: "F5"
        type: "TICKET"
        stops:
          - type: "START"
            authorization:
              type: "QR_AND_VEHICLE_NUMBER"
              token: "aMOPw0KGgoAAAANSUhEUgAAAH0AAAB9AQAAAACn+1GINAAApklEQVR4Xu2UMQ4EMQgD/QP+/0vK6zjsvayUMmavWxQpMAUBkwS12wcveAAkgNSCD3rR5Lkgoai3GUCMgWqbAEYR3HxAkZlzU/0MyBisYRsgI1ERFfcpBpA+ze6k56Cj7KTdXNigFWZvSOpsgqLfd18i2aAukXh9TXBNmdWt5gzA/oqzWkkN8HtA7G8CNOwYAiZt3wZixUfkA32OHNQq7Bxs9oI/gC/9fV8AVCkPjQAAAABJRU5ErkJggg=="
              valid_to: "2025-06-20T23:59:59.999Z"
              status: "CLAIMED"
