order:
    provider:
      id: PROVIDER_ID
    items:
      - id: CHILD_ITEM_ID_LOAN_1
        parent_item_id: ITEM_ID_PERSONAL_LOAN_2
        xinput:
          form:
            id: F02
            data:
              requestAmount:
                value: "232800"
              requestTerm:
                value: P5M
    fulfillments:
      - id: F1