save-data:
  message_id: "$.context.message_id"
  billing: "$.message.order.billing"
  payments: "$.message.order.payments[*]"
  buyer_side_fulfillment_ids: "$.message.order.fulfillments[*]"
  init_items: "$.message.order.items"
  init_tags: "$.message.order.tags"