save-data:
  latest_issue_payload: $.message.issue
  message_id: $.context.message_id
  last_action: $.context.action
  issue_action : $.message.issue.actions[*]
  issue_resolution: $.message.issue.resolutions[*]
  issue_level: $.message.issue.level
  issue_id: $.message.issue.id
  issue_status: $.message.issue.status
  # issue_id : "$.message.issue.id"
  # issue_created_at : "$.message.issue.created_at"
  # issue_refs : "$.message.issue.refs[*]"
  # issue_actors : "$.message.issue.actors[*]"
  # issue_source_id : "$.message.issue.source_id"
  # issue_complaint_id : "$.message.issue.complaint_id"
  # issue_respondent_id : "$.message.issue.respondent_id"
  # issue_descriptor_code : "$.message.issue.descriptor-code"
  # issue_descriptor_short_desc : "$.message.issue.descriptor.short_desc"
  # issue_descriptor_long_desc : "$.message.issue.descriptor.long_desc"
  # issue_descriptor_additional_desc_url : "$.message.issue.descriptor.additional_desc.url"
  # issue_descriptor_additional_desc_content_type : "$.message.issue.descriptor.additional_desc.content_type"


  # issue.level : "$.message.issue.level"

