save-data:
  order_id: "$.message.order.id"
  status: "$.message.order.status"
  updated_payments: "$.message.order.payments[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  created_at: "$.message.order.created_at"
  oldQuote: "$.message.order.quote.price.value"
  confirm_order: "$.message.order"
  tags: "$.message.order.tags"
  confirm_cancellation_terms: "$.message.order.cancellation_terms"
