save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  selected_items: "$.message.order.items[*]"
  item: "$.message.order.items[1]"
  selected_fulfillments: "$.message.order.fulfillments[*]"
  selected_provider: "$.message.order.provider"
  # billing: "$.message.order.billing"
  tags: "$.message.order.tags[*]" 