intent:
  provider:
    id: PROVIDER_ID
    items:
      - id: ITEM_ID_PERSONAL_LOAN_2
        xinput:
          form:
            id: F01
          form_response:
            status: SUCCESS
            submission_id: 0d62011a-619d-4a32-8c0c-533b9069cf98
  payment:
    collected_by: BPP
  tags:
    - display: false
      descriptor:
        name: BAP Terms of Engagement
        code: BAP_TERMS
      list:
        - descriptor:
            code: STATIC_TERMS
          value: >-
            https://bap.credit.becknprotocol.io/working-capital/loans/working-capital
        - descriptor:
            code: OFFLINE_CONTRACT
          value: 'true'
