save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  selected_items: "$.message.order.items[*]"
  item: "$.message.order.items[0]"
  selected_provider: "$.message.order.provider"
  last_select_status: "$.message.order.items[0].xinput.form_response.status"
  submission_id : "$.message.order.items[0].xinput.form_response.submission_id"
  form_id: "$.message.order.items[0].xinput.form.id"
