save-data:
  message_id: "$.context.message_id"
  updated_payments: "$.message.order.payments[*]"
  ttl: "$.context.ttl"
  buyer_side_fulfillment_ids: "$.message.order.fulfillments[*]"
  tags: "$.message.order.tags"
  confirm_tags: "$.message.order.tags"