codes:
  - code: 200
    action_id: search
    action: search
    default: FIS12/2.3.0/search/default.yaml
    message_id: true
  - code: 2001
    action_id: search1_purchase_finance
    action: search
    default: FIS12/2.3.0/search/default.yaml
    message_id: true
  - code: 2002
    action_id: search2_purchase_finance
    action: search
    default: FIS12/2.3.0/search2/default.yaml
    message_id: true
  - code: 2003
    action_id: search3_purchase_finance
    action: search
    default: FIS12/2.3.0/search3/default.yaml
    message_id: true
  - code: 2004
    action_id: search4_purchase_finance
    action: search
    default: FIS12/2.3.0/search4/default.yaml
    message_id: true
  - code: 2005
    action_id: master_search_unified_credit
    action: search
    default: FIS12/2.3.0/master_search/default.yaml
    message_id: true
  - code: 2006
    action_id: master_on_search_unified_credit
    action: on_search
    default: FIS12/2.3.0/master_on_search/default.yaml
    message_id: false
  - code: 201
    action_id: on_search
    action: on_search
    default: FIS12/2.3.0/on_search/default.yaml
    message_id: false
  - code: 2011
    action_id: on_search1_purchase_finance
    action: on_search
    default: FIS12/2.3.0/on_search/default.yaml
    message_id: false
  - code: 2012
    action_id: on_search2_purchase_finance
    action: on_search
    default: FIS12/2.3.0/on_search2/default.yaml
    message_id: false
  - code: 2013
    action_id: on_search3_purchase_finance
    action: on_search
    default: FIS12/2.3.0/on_search3/default.yaml
    message_id: false
  - code: 2014
    action_id: on_search4_purchase_finance
    action: on_search
    default: FIS12/2.3.0/on_search4/default.yaml
    message_id: false
  - code: 2015
    action_id: on_search5_purchase_finance
    action: on_search
    default: FIS12/2.3.0/on_search5/default.yaml
    message_id: false
  - code: 2016
    action_id: on_search6_purchase_finance
    action: on_search
    default: FIS12/2.3.0/on_search6/default.yaml
    message_id: false
  - code: 202
    action_id: select_purchase_finance
    action: select
    default: FIS12/2.3.0/select/default.yaml
    message_id: true
  - code: 2021
    action_id: select1_purchase_finance
    action: select
    default: FIS12/2.3.0/select1/default.yaml
    message_id: true
  - code: 2022
    action_id: select2_purchase_finance
    action: select
    default: FIS12/2.3.0/select2/default.yaml
    message_id: true
  - code: 203
    action_id: on_select_purchase_finance
    action: on_select
    default: FIS12/2.3.0/on_select/default.yaml
    message_id: false
  - code: 2031
    action_id: on_select1_purchase_finance
    action: on_select
    default: FIS12/2.3.0/on_select1/default.yaml
    message_id: false
  - code: 2032
    action_id: on_select2_purchase_finance
    action: on_select
    default: FIS12/2.3.0/on_select2/default.yaml
    message_id: false
  - code: 204
    action_id: init1_purchase_finance
    action: init
    default: FIS12/2.3.0/init/default.yaml
    message_id: true
  - code: 2041
    action_id: init2_purchase_finance
    action: init
    default: FIS12/2.3.0/init2/default.yaml
    message_id: true
  - code: 2042
    action_id: init3_purchase_finance
    action: init
    default: FIS12/2.3.0/init3/default.yaml
    message_id: true
  - code: 205
    action_id: on_init1_purchase_finance
    action: on_init
    default: FIS12/2.3.0/on_init/default.yaml
    message_id: false
  - code: 2051
    action_id: on_init2_purchase_finance
    action: on_init
    default: FIS12/2.3.0/on_init2/default.yaml
    message_id: false
  - code: 2052
    action_id: on_init3_purchase_finance
    action: on_init
    default: FIS12/2.3.0/on_init3/default.yaml
    message_id: false
  - code: 206
    action_id: confirm_purchase_finance
    action: confirm
    default: FIS12/2.3.0/confirm/default.yaml
    message_id: true
  
  - code: 207
    action_id: on_confirm_purchase_finance
    action: on_confirm
    default: FIS12/2.3.0/on_confirm/default.yaml
    message_id: false
  - code: 208
    action_id: update_purchase_finance
    action: update
    default: FIS12/2.3.0/update/default.yaml
    message_id: true
  - code: 2081
    action_id: update_missed_Emi
    action: update
    default: FIS12/2.3.0/update_missed_Emi/default.yaml
    message_id: true
  - code: 2082
    action_id: update_foreclosure
    action: update
    default: FIS12/2.3.0/update_foreclosure/default.yaml
    message_id: true
  - code: 2083
    action_id: update_prepart
    action: update
    default: FIS12/2.3.0/update_prepart/default.yaml
    message_id: true
  - code: 209
    action_id: on_update_purchase_finance
    action: on_update
    default: FIS12/2.3.0/on_update/default.yaml
    message_id: false
  - code: 2091
    action_id: on_update_missed_Emi
    action: on_update
    default: FIS12/2.3.0/on_update_missed_Emi/default.yaml
    message_id: true
  - code: 2092
    action_id: on_update_foreclosure
    action: on_update
    default: FIS12/2.3.0/on_update_foreclosure/default.yaml
    message_id: true
  - code: 2093
    action_id: on_update_prepart
    action: on_update
    default: FIS12/2.3.0/on_update_prepart/default.yaml
    message_id: true
  - code: 2101
    action_id: on_update1_unsolicited_purchase_finance
    action: on_update
    default: FIS12/2.3.0/on_update_unsolicited/default.yaml
    message_id: false
  - code: 2102
    action_id: on_update_unsolicited_cancel
    action: on_update
    default: FIS12/2.3.0/on_update_unsolicited_cancel/default.yaml
    message_id: false
  - code: 2103
    action_id: on_update_unsolicited_missed_Emi
    action: on_update
    default: FIS12/2.3.0/on_update_unsolicited_missed_Emi/default.yaml
    message_id: false
  - code: 2104
    action_id: on_update_unsolicited_foreclosure
    action: on_update
    default: FIS12/2.3.0/on_update_unsolicited_foreclosure/default.yaml
    message_id: false
  - code: 2105
    action_id: on_update_unsolicited_prepart
    action: on_update
    default: FIS12/2.3.0/on_update_unsolicited_prepart/default.yaml
    message_id: false
  - code: 211
    action_id: status_purchase_finance
    action: status
    default: FIS12/2.3.0/status/default.yaml
    message_id: true
  - code: 212
    action_id: on_status_purchase_finance
    action: on_status
    default: FIS12/2.3.0/on_status/default.yaml
    message_id: false
  - code: 213
    action_id: on_status_unsolicited
    action: on_status
    default: FIS12/2.3.0/on_status_unsolicited/default.yaml
    message_id: true

  - code: 214
    action_id: on_status_purchase_finance1
    action: on_status
    default: FIS12/2.3.0/on_status/default.yaml
    message_id: false
  - code: 215
    action_id: on_status_purchase_finance2
    action: on_status
    default: FIS12/2.3.0/on_status/default.yaml
    message_id: false
  - code: 221
    action_id: soft_cancel_purchase_finance
    action: cancel
    default: FIS12/2.3.0/soft_cancel/default.yaml
    message_id: true
  - code: 222
    action_id: soft_on_cancel_purchase_finance
    action: on_cancel
    default: FIS12/2.3.0/soft_on_cancel/default.yaml
    message_id: false
  - code: 223
    action_id: confirmed_cancel_purchase_finance
    action: cancel
    default: FIS12/2.3.0/confirmed_cancel/default.yaml
    message_id: true
  - code: 224
    action_id: confirmed_on_cancel_purchase_finance
    action: on_cancel
    default: FIS12/2.3.0/confirmed_on_cancel/default.yaml
    message_id: false

# personal loan default files
  
  - code: 300
    action_id: search_personal_loan
    action: search
    default: FIS12/2.3.0/personal_loan/search_personal_loan/default.yaml
    message_id: true
  - code: 301
    action_id: on_search_personal_loan
    action: on_search
    default: FIS12/2.3.0/personal_loan/on_search_personal_loan/default.yaml
    message_id: false
  - code: 302
    action_id: search_personal_loan_2
    action: search
    default: FIS12/2.3.0/personal_loan/search_personal_loan_2/default.yaml
    message_id: true
  - code: 303
    action_id: on_search_personal_loan_2
    action: on_search
    default: FIS12/2.3.0/personal_loan/on_search_personal_loan_2/default.yaml
    message_id: false
  - code: 304
    action_id: select_1_personal_loan
    action: select
    default: FIS12/2.3.0/personal_loan/select_1_personal_loan/default.yaml
    message_id: true
  - code: 305
    action_id: on_select_1_personal_loan
    action: on_select
    default: FIS12/2.3.0/personal_loan/on_select_1_personal_loan/default.yaml
    message_id: false
  - code: 306
    action_id: select_2_personal_loan
    action: select
    default: FIS12/2.3.0/personal_loan/select_2_personal_loan/default.yaml
    message_id: true
  - code: 307
    action_id: on_select_2_personal_loan
    action: on_select
    default: FIS12/2.3.0/personal_loan/on_select_2_personal_loan/default.yaml
    message_id: false
  - code: 308
    action_id: init_1_personal_loan
    action: init
    default: FIS12/2.3.0/personal_loan/init_1_personal_loan/default.yaml
    message_id: true
  - code: 309
    action_id: on_init_1_personal_loan
    action: on_init
    default: FIS12/2.3.0/personal_loan/on_init_1_personal_loan/default.yaml
    message_id: false
  - code: 310
    action_id: init_2_personal_loan
    action: init
    default: FIS12/2.3.0/personal_loan/init_2_personal_loan/default.yaml
    message_id: true
  - code: 311
    action_id: on_init_2_personal_loan
    action: on_init
    default: FIS12/2.3.0/personal_loan/on_init_2_personal_loan/default.yaml
    message_id: false
  - code: 312
    action_id: init_3_personal_loan
    action: init
    default: FIS12/2.3.0/personal_loan/init_3_personal_loan/default.yaml
    message_id: true
  - code: 313
    action_id: on_init_3_personal_loan
    action: on_init
    default: FIS12/2.3.0/personal_loan/on_init_3_personal_loan/default.yaml
    message_id: false
  - code: 314
    action_id: init_4_personal_loan
    action: init
    default: FIS12/2.3.0/personal_loan/init_4_personal_loan/default.yaml
    message_id: true
  - code: 315
    action_id: on_init_4_personal_loan
    action: on_init
    default: FIS12/2.3.0/personal_loan/on_init_4_personal_loan/default.yaml
    message_id: false
  - code: 316
    action_id: confirm_personal_loan
    action: confirm
    default: FIS12/2.3.0/personal_loan/confirm_personal_loan/default.yaml
    message_id: true
  - code: 317
    action_id: on_confirm_personal_loan
    action: on_confirm
    default: FIS12/2.3.0/personal_loan/on_confirm_personal_loan/default.yaml
    message_id: false
  - code: 318
    action_id: status_personal_loan
    action: status
    default: FIS12/2.3.0/personal_loan/status_personal_loan/default.yaml
    message_id: true
  - code: 319
    action_id: on_status_personal_loan
    action: on_status
    default: FIS12/2.3.0/personal_loan/on_status_personal_loan/default.yaml
    message_id: false
  - code: 320
    action_id: on_status_unsolicited_personal_loan
    action: on_status
    default: FIS12/2.3.0/personal_loan/on_status_unsolicited_personal_loan/default.yaml
    message_id: true
  - code: 321
    action_id: update_personal_loan_items
    action: update
    default: FIS12/2.3.0/personal_loan/update_personal_loan_items/default.yaml
    message_id: true
  - code: 322
    action_id: on_update_personal_loan_items
    action: on_update
    default: FIS12/2.3.0/personal_loan/on_update_personal_loan_items/default.yaml
    message_id: false
  - code: 323
    action_id: on_update_unsolicited_personal_loan
    action: on_update
    default: FIS12/2.3.0/personal_loan/on_update_unsolicited_personal_loan/default.yaml
    message_id: false
  - code: 324
    action_id: search_personal_loan_3
    action: search
    default: FIS12/2.3.0/personal_loan/search_personal_loan_3/default.yaml
    message_id: true
  - code: 325
    action_id: on_search_personal_loan_3
    action: on_search
    default: FIS12/2.3.0/personal_loan/on_search_personal_loan_3/default.yaml
    message_id: false
  - code: 326
    action_id: search_personal_loan_4
    action: search
    default: FIS12/2.3.0/personal_loan/search_personal_loan_4/default.yaml
    message_id: true
  - code: 327
    action_id: on_search_personal_loan_4
    action: on_search
    default: FIS12/2.3.0/personal_loan/on_search_personal_loan_4/default.yaml
    message_id: false
  - code: 328
    action_id: search_personal_loan_5
    action: search
    default: FIS12/2.3.0/personal_loan/search_personal_loan_5/default.yaml
    message_id: true   
  - code: 329
    action_id: on_search_personal_loan_5
    action: on_search
    default: FIS12/2.3.0/personal_loan/on_search_personal_loan_5/default.yaml
    message_id: false


#Invoice based loan

  - code: 330
    action_id: search_invoice_loan
    action: search
    default: FIS12/2.3.0/invoice_loan/search_invoice_loan/default.yaml
    message_id: true
  - code: 331
    action_id: on_search_invoice_loan
    action: on_search
    default: FIS12/2.3.0/invoice_loan/on_search_invoice_loan/default.yaml
    message_id: false
  - code: 332
    action_id: search_invoice_loan_2
    action: search
    default: FIS12/2.3.0/invoice_loan/search_invoice_loan_2/default.yaml
    message_id: true
  - code: 333
    action_id: on_search_invoice_loan_2
    action: on_search
    default: FIS12/2.3.0/invoice_loan/on_search_invoice_loan_2/default.yaml
    message_id: false
  - code: 334
    action_id: select_1_invoice_loan
    action: select
    default: FIS12/2.3.0/invoice_loan/select_1_invoice_loan/default.yaml
    message_id: true
  - code: 335
    action_id: on_select_1_invoice_loan
    action: on_select
    default: FIS12/2.3.0/invoice_loan/on_select_1_invoice_loan/default.yaml
    message_id: false
  - code: 336
    action_id: select_2_invoice_loan
    action: select
    default: FIS12/2.3.0/invoice_loan/select_2_invoice_loan/default.yaml
    message_id: true
  - code: 337
    action_id: on_select_2_invoice_loan
    action: on_select
    default: FIS12/2.3.0/invoice_loan/on_select_2_invoice_loan/default.yaml
    message_id: false
  - code: 338
    action_id: init_1_invoice_loan
    action: init
    default: FIS12/2.3.0/invoice_loan/init_1_invoice_loan/default.yaml
    message_id: true
  - code: 339
    action_id: on_init_1_invoice_loan
    action: on_init
    default: FIS12/2.3.0/invoice_loan/on_init_1_invoice_loan/default.yaml
    message_id: false
  - code: 340
    action_id: init_2_invoice_loan
    action: init
    default: FIS12/2.3.0/invoice_loan/init_2_invoice_loan/default.yaml
    message_id: true
  - code: 341
    action_id: on_init_2_invoice_loan
    action: on_init
    default: FIS12/2.3.0/invoice_loan/on_init_2_invoice_loan/default.yaml
    message_id: false
  - code: 342
    action_id: init_3_invoice_loan
    action: init
    default: FIS12/2.3.0/invoice_loan/init_3_invoice_loan/default.yaml
    message_id: true
  - code: 343
    action_id: on_init_3_invoice_loan
    action: on_init
    default: FIS12/2.3.0/invoice_loan/on_init_3_invoice_loan/default.yaml
    message_id: false
  - code: 344
    action_id: init_4_invoice_loan
    action: init
    default: FIS12/2.3.0/invoice_loan/init_4_invoice_loan/default.yaml
    message_id: true
  - code: 345
    action_id: on_init_4_invoice_loan
    action: on_init
    default: FIS12/2.3.0/invoice_loan/on_init_4_invoice_loan/default.yaml
    message_id: false
  - code: 346
    action_id: init_5_invoice_loan
    action: init
    default: FIS12/2.3.0/invoice_loan/init_5_invoice_loan/default.yaml
    message_id: true
  - code: 347
    action_id: on_init_5_invoice_loan
    action: on_init
    default: FIS12/2.3.0/invoice_loan/on_init_5_invoice_loan/default.yaml
    message_id: false
  - code: 348
    action_id: confirm_invoice_loan
    action: confirm
    default: FIS12/2.3.0/invoice_loan/confirm_invoice_loan/default.yaml
    message_id: true
  - code: 349
    action_id: on_confirm_invoice_loan
    action: on_confirm
    default: FIS12/2.3.0/invoice_loan/on_confirm_invoice_loan/default.yaml
    message_id: false
  - code: 350
    action_id: status_invoice_loan
    action: status
    default: FIS12/2.3.0/invoice_loan/status_invoice_loan/default.yaml
    message_id: true
  - code: 351
    action_id: on_status_invoice_loan
    action: on_status
    default: FIS12/2.3.0/invoice_loan/on_status_invoice_loan/default.yaml
    message_id: false
  - code: 352
    action_id: on_status_unsolicited_invoice_loan
    action: on_status
    default: FIS12/2.3.0/invoice_loan/on_status_unsolicited_invoice_loan/default.yaml
    message_id: true
  - code: 353
    action_id: update_invoice_loan_items
    action: update
    default: FIS12/2.3.0/invoice_loan/update_invoice_loan_items/default.yaml
    message_id: true
  - code: 354
    action_id: on_update_invoice_loan_items
    action: on_update
    default: FIS12/2.3.0/invoice_loan/on_update_invoice_loan_items/default.yaml
    message_id: false
  - code: 355
    action_id: on_update_unsolicited_invoice_loan
    action: on_update
    default: FIS12/2.3.0/invoice_loan/on_update_unsolicited_invoice_loan/default.yaml
    message_id: false
  - code: 356
    action_id: search_invoice_loan_3
    action: search
    default: FIS12/2.3.0/invoice_loan/search_invoice_loan_3/default.yaml
    message_id: true
  - code: 357
    action_id: on_search_invoice_loan_3
    action: on_search
    default: FIS12/2.3.0/invoice_loan/on_search_invoice_loan_3/default.yaml
    message_id: false
  