intent:
  provider:
    id: PROVIDER_ID
    items:
      - id: ITEM_ID_LOAN_2
        xinput:
          form:
            id: F01
          form_response:
            status: SUCCESS
            submission_id: 25e4ddd6-6e0b-4f39-9a5f-b24a6e92662f
  tags:
    - display: false
      descriptor:
        name: BAP Terms of Engagement
        code: BAP_TERMS
      list:
        - descriptor:
            code: STATIC_TERMS
          value: >-
            https://bap.credit.becknprotocol.io/working-capital/loans/working-capital
        - descriptor:
            code: OFFLINE_CONTRACT
          value: 'true'
