intent:
  provider:
    id: PROVIDER_ID
    items:
      - id: ITEM_ID_LOAN_2
        xinput:
          form:
            id: F01
            data:
              udyamNumber:
                value: UDYAM-XX-00-0000000
              contactNumber:
                value: '+919123456789'
              email:
                value: example@gmail.com
              gstinProfile:
                format: .json
                validity: P5D
                value: 'https://bap.credit.becknprotocol.org/uploads/gstinProfile'
              gstr1:
                format: .json
                validity: P5D
                value: 'https://bap.credit.becknprotocol.org/uploads/gstinProfile'
              gstr2:
                format: .json
                validity: P5D
                value: 'https://bap.credit.becknprotocol.org/uploads/gstinProfile'
              gstr3:
                format: .json
                validity: P5D
                value: 'https://bap.credit.becknprotocol.org/uploads/gstinProfile'
              gstr4:
                format: .json
                validity: P5D
                value: 'https://bap.credit.becknprotocol.org/uploads/gstinProfile'
              gstr5:
                format: .json
                validity: P5D
                value: 'https://bap.credit.becknprotocol.org/uploads/gstinProfile'
              bureauConsent:
                value: 'true'
              aa_id:
                value: 9999999999@finvu
              tnc:
                value: 'true'
  tags:
    - display: false
      descriptor:
        name: BAP Terms of Engagement
        code: BAP_TERMS
      list:
        - descriptor:
            code: STATIC_TERMS
          value: >-
            https://bap.credit.becknprotocol.io/working-capital/loans/working-capital
        - descriptor:
            code: OFFLINE_CONTRACT
          value: 'true'
