order:
  provider:
    id: PROVIDER_ID
    descriptor:
      images:
        - url: https://www.icicibank.com/content/dam/icicibank/india/assets/images/header/logo.png
          size_type: sm
      name: ICICI Bank
      short_desc: ICICI Bank Ltd
      long_desc: ICICI Bank Ltd, India.
    tags:
      - descriptor:
          code: CONTACT_INFO
          name: Contact Info
        list:
          - descriptor:
              code: GRO_NAME
              name: Gro name
            value: ICICI
          - descriptor:
              code: GRO_EMAIL
              name: Gro email
            value: lifeline@iciciprulife.com
          - descriptor:
              code: GRO_CONTACT_NUMBER
              name: Gro contact number
            value: "1860 266 7766"
          - descriptor:
              code: GRO_DESIGNATION
              name: Gro Designation
            value: Nodal Grievance Redressal Officer
          - descriptor:
              code: GRO_ADDRESS
              name: Gro Address
            value: One Indiabulls centre, Tower 1, 18th Floor Jupiter mill compound 841, Senapati Bapat Marg, Elphinstone Road, Mumbai 400013
          - descriptor:
              code: CUSTOMER_SUPPORT_LINK
              name: Customer support link
            value: https://buy.iciciprulife.com/buy/GrievanceRedStep.htm?execution=e1s1
          - descriptor:
              code: CUSTOMER_SUPPORT_CONTACT_NUMBER
              name: Customer support contact number
            value: "1800 1080"
          - descriptor:
              code: CUSTOMER_SUPPORT_EMAIL
              name: Customer support email
            value: customer.care@icicibank.com
      - descriptor:
          code: LSP_INFO
          name: Lsp Info
        list:
          - descriptor:
              code: LSP_NAME
              name: Lsp name
            value: ICICI_LSP
          - descriptor:
              code: LSP_EMAIL
              name: Lsp email
            value: lsp@iciciprulife.com
          - descriptor:
              code: LSP_CONTACT_NUMBER
              name: Lsp contact number
            value: "1860 266 7766"
          - descriptor:
              code: LSP_ADDRESS
              name: Lsp Address
            value: One Indiabulls centre, Tower 1, 18th Floor Jupiter mill compound 841, Senapati Bapat Marg, Elphinstone Road, Mumbai 400013

  items:
    - id: ITEM_ID_GOLD_LOAN_1
      descriptor:
        code: LOAN
        name: Gold Loan
      tags:
        - descriptor:
            code: CONSENT_INFO
            name: Consent Information
          list:
            - descriptor:
                code: CONSENT_HANDLER
                name: Consent Handler
              value: 50635a60-7d85-441a-85f4-86f734ca4e4c
          display: false
      xinput:
        form:
          id: F01
        form_response:
          status: PENDING
          submission_id: F01_SUBMISSION_ID
