save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  verification_status: "$..form.url"
  Ekyc_details_form: "$..form.url"
  items: "$.message.order.items[*]"
  provider_id: "$.message.order.provider.id"
  item: "$.message.order.items[0]"
  selected_provider: "$.message.order.provider"
  quote_id: "$.message.order.quote.id"
  quote: "$.message.order.quote"
  form_id: "$.message.order.items[0].xinput.form.id"