message:
  order:
    provider:
      id: P1
      descriptor:
        name: Delhi Metro Rail Limited
        images:
          - url: https://delhimetrorail.com/logos/logo.icon
    items:
      - id: I3
        category_ids:
          - C3
        descriptor:
          name: Metro Card Purchase
          code: PURCHASE
          images:
            - url: https://delhimetrorail.com/logos/logo.ico
        fulfillment_ids:
          - F2
        price:
          currency: INR
          value: "200"
    fulfillments:
      - id: F2
        stops:
          - instructions:
              name: How to use?
              short_desc: short description about how to use?
              long_desc: Description about how to use?
        type: PASS
    cancellation_terms:
      - external_ref:
          mimetype: text/html
          url: https://transitsolutions.com/mf/tnc.html
    quote:
      id: Q1
      price:
        value: "220"
        currency: INR
      breakup:
        - title: BASE_FARE
          item:
            id: I1
            price:
              currency: INR
              value: "200"
        - title: CONVENIENCE_FEE
          price:
            currency: INR
            value: "10"
        - title: TAX
          price:
            currency: INR
            value: "10"
          item:
            tags:
              - descriptor:
                  code: TAX
                list:
                  - descriptor:
                      code: CGST
                    value: "2%"
                  - descriptor:
                      code: SGST
                    value: "2%"
        - title: OTHER_CHARGES
          price:
            currency: INR
            value: "0"
          item:
            tags:
              - descriptor:
                  code: OTHER_CHARGES
                list:
                  - descriptor:
                      code: SURCHARGE
                    value: "0"
        - title: OFFER
          price:
            currency: INR
            value: "0"
