update_target: items
order:
  id: 993f4b87-bc33-4242-aa8c-6d1806030c3c_ORDER_ID
  items:
    - id: CHILD_ITEM_ID_LOAN_1
      parent_item_id: ITEM_ID_LOAN_2
      xinput:
        form:
          id: F11
        form_response:
          status: SUCCESS
          submission_id: 1b2d7b84-712c-49cf-b0a3-f9c95e8ab5c4
