message:
  catalog:
    descriptor:
      name: Transit Solutions
      images:
        - url: "https://transitsolutions.in/logos/logo.ico"
          size_type: xs
    providers:
      - id: P1
        descriptor:
          name: Delhi Transport Corporation
          images:
            - url: >-
                https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
              size_type: xs
        items:
          - id: I1
            descriptor:
              name: Monthly Pass
              code: PASS
              images:
                - url: https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
                  size_type: xs
            fulfillment_ids:
              - F1
            price:
              currency: INR
              value: "200"
            quantity:
              maximum:
                count: 1
              minimum:
                count: 1
            time:
              label: Validity
              duration: P1M
        fulfillments:
          - id: F1
            type: PASS
            customer:
              person:
                creds:
                  - type: PAN
                  - type: AADHAR
                  - type: DL
                  - type: VOTER_ID
            stops:
              - type: START
                location:
                  descriptor:
                    code: std:011
                  gps: 28.666576, 77.233332
                id: "1"
            vehicle:
              category: BUS
              variant: AC
        payments:
          - collected_by: BAP
            tags:
              - descriptor:
                  code: BUYER_FINDER_FEES
                display: false
                list:
                  - descriptor:
                      code: BUYER_FINDER_FEES_PERCENTAGE
                    value: "1"
              - descriptor:
                  code: SETTLEMENT_TERMS
                display: false
                list:
                  - descriptor:
                      code: SETTLEMENT_WINDOW
                    value: P30D
                  - descriptor:
                      code: SETTLEMENT_BASIS
                    value: INVOICE_RECEIPT
                  - descriptor:
                      code: MANDATORY_ARBITRATION
                    value: "TRUE"
                  - descriptor:
                      code: COURT_JURISDICTION
                    value: New Delhi
                  - descriptor:
                      code: STATIC_TERMS
                    value: "https://www.abc.com/settlement-terms/"
