message:
  intent:
    fulfillment:
      vehicle:
        category: METRO
    payment:
      collected_by: BAP
    tags:
      - descriptor:
          code: BAP_TERMS
          name: BAP Terms of Engagement
        display: false
        list:
          - descriptor:
              code: BUYER_FINDER_FEES_PERCENTAGE
            value: "1"
          - descriptor:
              code: STATIC_TERMS
            value: https://api.example-bap.com/booking/terms
          - descriptor:
              code: DELAY_INTEREST
            value: "2.5"
