message:
  order:
    items:
      - id: I8
        descriptor:
          name: Weekly Pass
          code: PASS
          images:
            - url: >-
                https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
              size_type: xs
        fulfillment_ids:
          - F1
        price:
          currency: INR
          value: '100'
        quantity:
          selected:
            count: 1
        time:
          label: Validity
          duration: P7D
          timestamp: '2021-03-23T10:00:40.065Z'
          range:
            start: '2021-03-23T10:00:40.065Z'
            end: '2021-03-29T17:00:40.065Z'
    provider:
      id: P1
      descriptor:
        name: Delhi Transport Corporation
        images:
          - url: >-
              https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
            size_type: xs
    fulfillments:
      - id: F1
        type: PASS
        customer:
          person:
            creds:
              - type: PAN
                id: YKPYS1412V
        stops:
          - type: START
            location:
              descriptor:
                code: 'std:011'
              gps: '28.666576, 77.233332'
            id: '1'
        vehicle:
          category: BUS
          variant: AC
    cancellation_terms:
      - cancel_by:
          duration: PT60M
        cancellation_fee:
          percentage: '0'
    billing:
      name: John Doe
      email: john.doe@example.com
      phone: +91-9897867564
    quote:
      price:
        value: '100'
        currency: INR
      breakup:
        - title: BASE_FARE
          item:
            id: I1
            price:
              currency: INR
              value: '100'
            quantity:
              selected:
                count: 1
          price:
            currency: INR
            value: '100'
        - title: OFFER
          price:
            currency: INR
            value: '0'
        - title: TOLL
          price:
            currency: INR
            value: '0'
    payments:
      - id: PA1
        collected_by: BAP
        status: NOT-PAID
        type: PRE-ORDER
        params:
          bank_code: XXXXXXXX
          bank_account_number: xxxxxxxxxxxxxx
          virtual_payment_address: 9988199772@okicic
        tags:
          - descriptor:
              code: BUYER_FINDER_FEES
            display: false
            list:
              - descriptor:
                  code: BUYER_FINDER_FEES_PERCENTAGE
                value: '1'
          - descriptor:
              code: SETTLEMENT_TERMS
            display: false
            list:
              - descriptor:
                  code: SETTLEMENT_WINDOW
                value: PT60M
              - descriptor:
                  code: SETTLEMENT_BASIS
                value: Delivery
              - descriptor:
                  code: SETTLEMENT_TYPE
                value: upi
              - descriptor:
                  code: MANDATORY_ARBITRATION
                value: 'TRUE'
              - descriptor:
                  code: COURT_JURISDICTION
                value: New Delhi
              - descriptor:
                  code: DELAY_INTEREST
                value: '2.5'
              - descriptor:
                  code: STATIC_TERMS
                value: 'https://www.abc.com/settlement-terms/'
              - descriptor:
                  code: SETTLEMENT_AMOUNT
                value: '12505'
    tags:
      - descriptor:
          code: SCHEDULED_INFO
        display: false
        list:
          - descriptor:
              code: GTFS
            value: 'https://api.transit-solutions/gtfs-realtime'
