save-data:
  message_id: "$.context.message_id"
  billing: "$.message.order.billing"
  payments: "$.message.order.payments[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  provider_id: "$.message.order.provider.id"
