order:
  id: LOAN_LEAD_ID_OR_SIMILAR_ORDER_ID
  status: COMPLETE

  provider:
    id: PROVIDER_ID
    descriptor:
      name: ICICI Bank
      short_desc: ICICI Bank Ltd
      long_desc: ICICI Bank Ltd, India.
      images:
        - url: https://www.icicibank.com/content/dam/icicibank/india/assets/images/header/logo.png
          size_type: sm
    tags:
      - descriptor:
          code: CONTACT_INFO
          name: Contact Info
        list:
          - descriptor:
              code: GRO_NAME
              name: Gro name
            value: ICICI
          - descriptor:
              code: GRO_EMAIL
              name: Gro email
            value: lifeline@iciciprulife.com
          - descriptor:
              code: GRO_CONTACT_NUMBER
              name: Gro contact number
            value: "1860 266 7766"
          - descriptor:
              code: CUSTOMER_SUPPORT_LINK
              name: Customer support link
            value: https://buy.iciciprulife.com/buy/GrievanceRedStep.htm?execution=e1s1
          - descriptor:
              code: CUSTOMER_SUPPORT_CONTACT_NUMBER
              name: Customer support contact number
            value: "1800 1080"
          - descriptor:
              code: CUSTOMER_SUPPORT_EMAIL
              name: Customer support email
            value: customer.care@icicibank.com

      - descriptor:
          code: LSP_INFO
          name: Lsp Info
        list:
          - descriptor:
              code: LSP_NAME
              name: Lsp name
            value: ICICI_LSP
          - descriptor:
              code: LSP_EMAIL
              name: Lsp email
            value: lsp@iciciprulife.com
          - descriptor:
              code: LSP_CONTACT_NUMBER
              name: Lsp contact number
            value: "1860 266 7766"
          - descriptor:
              code: LSP_ADDRESS
              name: Lsp Address
            value: One Indiabulls centre, Tower 1, 18th Floor Jupiter mill compound 841, Senapati Bapat Marg, Elphinstone Road, Mumbai 400013

  items:
    - id: CHILD_ITEM_ID_I1
      parent_item_id: ITEM_ID_ELECTRONICS
      descriptor:
        code: LOAN
        name: Loan
      category_ids:
        - "101123"
        - "101125"
      price:
        currency: INR
        value: "70000"
      fulfillment_ids:
        - F1
        - F2

  fulfillments:
    - id: F1
      type: LOAN
      state:
        descriptor:
          code: SANCTIONED
      customer:
        person:
          name: John Doe
        contact:
          phone: "+91-9999999999"
          email: john.doe@example.com

    - id: F2
      type: BASE_ORDER
      state:
        descriptor:
          code: PLACED
      customer:
        person:
          name: John Doe
          creds:
            - type: IMEI
              id: "324124135678567"
        contact:
          phone: "+91-9999999999"
          email: john.doe@example.com

  quote:
    id: 993f4b87-bc33-4242-aa8c-6d1806030c3c
    price:
      currency: INR
      value: "70000"
    breakup:
      - title: PRINCIPAL_AMOUNT
        price:
          value: "65000"
          currency: INR
      - title: INTEREST_AMOUNT
        price:
          value: "4000"
          currency: INR
      - title: PROCESSING_FEE
        price:
          value: "500"
          currency: INR
      - title: OTHER_UPFRONT_CHARGES
        price:
          value: "0"
          currency: INR
      - title: INSURANCE_CHARGES
        price:
          value: "500"
          currency: INR
      - title: NET_DISBURSED_AMOUNT
        price:
          value: "64000"
          currency: INR
      - title: OTHER_CHARGES
        price:
          value: "0"
          currency: INR
      - title: FORECLOSURE_CHARGES
        price:
          value: "148"
          currency: INR
      - title: OUTSTANDING_PRINCIPAL
        price:
          value: "18572"
          currency: INR
      - title: OUTSTANDING_INTEREST
        price:
          value: "1142"
          currency: INR
    ttl: P15D

  cancellation_terms:
    - fulfillment_state:
        descriptor:
          code: SANCTIONED
      cancellation_fee:
        percentage: "3%"
    - external_ref:
        mimetype: text/html
        url: https://bpp.credit.becknprotocol.org/tnc.html
    - fulfillment_state:
        descriptor:
          code: DISBURSED
      cancellation_fee:
        percentage: "5%"

  payments:
    - id: PAYMENT_ID_PURCHASE_FINANCE
      type: POST_FULFILLMENT
      status: PAID
      params:
        amount: "29571"
        currency: INR
        transaction_id: 57aceecb-e73d-4b1e-9257-a69b10b33cd9
      time:
        label: FORECLOSURE
        timestamp: 2024-10-01T04:00:00.000Z

    - id: PAYMENT_ID_DOWNPAYMENT
      type: PRE_ORDER
      status: PAID
      collected_by: BPP
      params:
        amount: "1000"
        currency: INR
        transaction_id: 3b5a664d-077e-47f0-96d1-06e68d397c78

    - id: INSTALLMENT_ID_PURCHASE_FINANCE
      type: POST_FULFILLMENT
      status: DEFERRED
      params:
        amount: "9857"
        currency: INR
      time:
        label: INSTALLMENT
        range:
          start: 2024-10-01T04:00:00.000Z
          end: 2024-10-31T23:59:59.999Z

  documents:
    - descriptor:
        code: LOAN_AGREEMENT
        name: Loan Agreement Document
        short_desc: Download your Loan Agreement document here
        long_desc: A Loan Agreement Document is a legal contract outlining terms such as loan amount, interest rate, repayment schedule, and collateral, binding a lender and borrower in a formal financial arrangement.
      mime_type: application/pdf
      url: https://lender.com/loan/loan-agreement/O1.pdf

    - descriptor:
        code: LOAN_CANCELLATION
        name: Loan Cancellation Document
        short_desc: Download your Loan Cancellation document here
        long_desc: A Loan Cancellation Document is a formal agreement used to terminate an existing loan, releasing the borrower from repayment obligations and confirming the loan's cancellation.
      mime_type: application/pdf
      url: https://lender.com/loan/loan-cancellation/O1.pdf

  created_at: 2024-05-06T04:19:20.443Z
  updated_at: 2024-05-06T04:20:25.443Z
