save-data:
  latest_issue_payload: $.message.issue
  message_id: $.context.message_id
  last_action: $.context.action
  issue_action : $.message.issue.actions[*]
  issue_resolution: $.message.issue.resolutions[*]
  issue_level: $.message.issue.level
  issue_id: $.message.issue.id
  issue_status: $.message.issue.status
  # _____________________IGM1.0.0______________________________
  issue_created_at: $.message.issue.created_at
  issue_category: $.message.issue.category
  issue_sub_category: $.message.issue.sub_category
  issue_complaint_info: $.message.issue.complainant_info
  issue_order_details: $.message.issue.order_details
  issue_description: $.message.issue.description
  issue_source: $.message.issue.source
  issue_expected_response_time: $.message.issue.expected_response_time
  issue_expected_resolution_time: $.message.issue.expected_resolution_time
  issue_actions: $.message.issue.issue_actions
  issue_issue_type: $.message.issue.issue_type