message:
  catalog:
    descriptor:
      name: Transit Solutions
      images:
        - url: https://transitsolutions.in/logos/logo.ico
    providers:
      - id: P1
        categories:
          - descriptor:
              name: Wallet
              code: WALLET
            id: C3
        locations:
          - id: L1
            city:
              code: "std:011"
        time:
          range:
            start: "2023-09-14T05:30:00.000Z"
            end: "2023-09-14T23:30:00.000Z"
        descriptor:
          name: Delhi Metro Rail Limited
          images:
            - url: https://delhimetrorail.com/logos/logo.ico
        items:
          - id: I3
            category_ids:
              - C3
            descriptor:
              name: Metro Card Purchase
              code: PURCHASE
              images:
                - url: https://delhimetrorail.com/logos/logo.ico
            fulfillment_ids:
              - F2
            price:
              currency: INR
              value: "500"
              minimum_value: "100"
              maximum_value: "500"
        fulfillments:
          - id: F2
            type: PASS
            stops:
              - instructions:
                  name: How to use?
                  short_desc: short description about how to use?
                  long_desc: description about how to use?
        payments:
          - collected_by: BPP
        tags:
          - descriptor:
              code: ADDITIONAL_APIS
            display: false
            list:
              - descriptor:
                  code: GTFS_RT
                value: https://metro-transit/gtfs-realtime
              - descriptor:
                  code: GTFS_ST
                value: https://metro-transit/gtfs-static
              - descriptor:
                  code: WALLET_BALANCE_CHECK
                  name: The CARD_NUMBER represents the Metro card number and is used to check the wallet balance via the API.
                value: https://metro-transit/wallet/balance/{CARD_NUMBER}
    tags:
      - descriptor:
          code: BPP_TERMS
          name: BPP Terms of Engagement
        display: false
        list:
          - descriptor:
              code: BUYER_FINDER_FEES_PERCENTAGE
            value: "1"
          - descriptor:
              code: SETTLEMENT_WINDOW
            value: P30D
          - descriptor:
              code: SETTLEMENT_BASIS
            value: INVOICE_RECEIPT
          - descriptor:
              code: MANDATORY_ARBITRATION
            value: "TRUE"
          - descriptor:
              code: COURT_JURISDICTION
            value: New Delhi
          - descriptor:
              code: STATIC_TERMS
            value: https://api.example-bpp.com/booking/terms
