save-data:
  transaction_id: $.context.transaction_id
  message_id: $.context.message_id
  order_id: $.message.order.id
  order_state: $.message.order.state
  order: $.message.order
  quote: $.message.order.quote
  quote_id: $.message.order.quote.id
  item: $.message.order.items[0]
  payments: $.message.order.payments
