order:
  provider:
    id: PROVIDER_ID
    descriptor:
      images:
        - url: >-
            https://www.icicibank.com/content/dam/icicibank/india/assets/images/header/logo.png
          size_type: sm
      name: ICICI Bank
      short_desc: ICICI Bank Ltd
      long_desc: 'ICICI Bank Ltd, India.'
    tags:
      - descriptor:
          code: CONTACT_INFO
          name: Contact Info
        list:
          - descriptor:
              code: GRO_NAME
              name: Gro name
            value: ICICI
          - descriptor:
              code: GRO_EMAIL
              name: Gro email
            value: lifeline@iciciprulife.com
          - descriptor:
              code: GRO_CONTACT_NUMBER
              name: Gro contact number
            value: 1860 266 7766
          - descriptor:
              code: GRO_DESIGNATION
              name: Gro Designation
            value: Nodal Grievance Redressal Officer
          - descriptor:
              code: GRO_ADDRESS
              name: Gro Address
            value: >-
              One Indiabulls centre, Tower 1, 18th Floor Jupiter mill compound
              841, Senapati Bapat Marg, Elphinstone Road, Mumbai 400013
          - descriptor:
              code: CUSTOMER_SUPPORT_LINK
              name: Customer support link
            value: >-
              https://buy.iciciprulife.com/buy/GrievanceRedStep.htm?execution=e1s1
          - descriptor:
              code: CUSTOMER_SUPPORT_CONTACT_NUMBER
              name: Customer support contact number
            value: 1800 INR 1080
          - descriptor:
              code: CUSTOMER_SUPPORT_EMAIL
              name: Customer support email
            value: customer.care@icicibank.com
      - descriptor:
          code: LSP_INFO
          name: Lsp Info
        list:
          - descriptor:
              code: LSP_NAME
              name: Lsp name
            value: ICICI_LSP
          - descriptor:
              code: LSP_EMAIL
              name: Lsp email
            value: lsp@iciciprulife.com
          - descriptor:
              code: LSP_CONTACT_NUMBER
              name: Lsp contact number
            value: 1860 266 7766
          - descriptor:
              code: LSP_ADDRESS
              name: Lsp Address
            value: >-
              One Indiabulls centre, Tower 1, 18th Floor Jupiter mill compound
              841, Senapati Bapat Marg, Elphinstone Road, Mumbai 400013
  items:
    - id: CHILD_ITEM_ID_LOAN_1
      parent_item_id: ITEM_ID_PERSONAL_LOAN_2
      descriptor:
        code: LOAN
        name: Personal Loan with AA
      category_ids:
        - '101111'
        - '101212'
      fulfillment_ids:
        - F1
      price:
        currency: INR
        value: '232800'
      xinput:
        head:
          descriptor:
            name: Loan agreement
            code: LOAN_AGREEMENT
          headings:
            - KYC
            - EMANDATE
            - LOAN_AGREEMENT
        form:
          id: F06
          mime_type: application/html
          url: 'https://bpp.credit.becknprotocol.org/xinput/formid/F06'
          resubmit: false
          multiple_sumbissions: false
        required: true
      tags:
        - descriptor:
            code: LOAN_INFO
            name: Information
          list:
            - descriptor:
                code: INTEREST_RATE
                name: Interest Rate
                short_desc: Loans starting from 12% (p.a)
              value: 12 %
            - descriptor:
                code: TERM
                name: Loan Term
                short_desc: Loans Duration 5 months
              value: P5M
            - descriptor:
                code: INTEREST_RATE_TYPE
                name: Interest rate type
                short_desc: Fixed Interest type
              value: FIXED
            - descriptor:
                code: APPLICATION_FEE
                name: Application Fees
                short_desc: Application Fees
              value: 1000 INR
            - descriptor:
                code: FORECLOSURE_FEE
                name: Foreclosure Penalty
                short_desc: Loan Foreclosure Penalty
              value: 0.5 %
            - descriptor:
                code: FORECLOSURE_FEE
                name: Foreclosure Penalty
                short_desc: Loan Foreclosure Penalty
              value: 0.5 %
            - descriptor:
                code: INTEREST_RATE_CONVERSION_CHARGE
                name: interest rate conversion charges
                short_desc: Interest rate conversion charges
              value: 1000 INR
            - descriptor:
                code: INTEREST_RATE_CONVERSION_CHARGE
                name: interest rate conversion charges
                short_desc: Interest rate conversion charges
              value: 1000 INR
            - descriptor:
                code: DELAY_PENALTY_FEE
                name: Delayed payments penalty
                short_desc: Delayed payments penalty
              value: 5 %
            - descriptor:
                code: OTHER_PENALTY_FEE
                name: Other Penal Charges
                short_desc: Other Penal Charges
              value: 1 %
            - descriptor:
                code: ANNUAL_PERCENTAGE_RATE
                name: Annual Percentage Rate
                short_desc: >-
                  Effective annualized interest rate in percentage computed on
                  net disbursed amount using IRR approach and reducing balance
                  method
              value: 5 %
            - descriptor:
                code: REPAYMENT_FREQUENCY
                name: Repayment Frequency
                short_desc: Repayment Frequency by borrower
              value: P1M
            - descriptor:
                code: NUMBER_OF_INSTALLMENTS
                name: Number of installments of repayment
                short_desc: >-
                  Number of installments borrower has to make to payback the
                  loan
              value: '45'
            - descriptor:
                code: TNC_LINK
                name: Terms & Conditions
                short_desc: Terms and Conditions
              value: 'https://icicibank.com/loan/tnc.html'
            - descriptor:
                code: COOL_OFF_PERIOD
                name: cool off period
                short_desc: >-
                  Cooling off/look-up period during which borrower shall not be
                  charged any penalty
              value: P30D
            - descriptor:
                code: INSTALLMENT_AMOUNT
                name: Installment amount
                short_desc: Each installment amount of repayment
              value: 46360 INR
            - descriptor:
                code: KFS_LINK
                name: Key Facts Statement Link
                short_desc: >-
                  A link provided by the BPP points to a Key Fact Statement
                  (KFS) document related to a loan. When accessed, the document
                  is returned in text/html format, with the loan details
                  organized in a standard HTML table. This format makes it easy
                  for the buyer's app to read and reformat the information as
                  needed. For more details, refer to the \"KFS_LINK format\"
                  document in the \"feature-ui\" section.
              value: 'https://icicibank.com/loan/kfs-terms'
  quote:
    id: dfc89ac0-0738-4963-a0f0-1be855440675
    price:
      currency: INR
      value: '232800'
    breakup:
      - title: PRINCIPAL_AMOUNT
        price:
          value: '200000'
          currency: INR
      - title: INTEREST_AMOUNT
        price:
          value: '30000'
          currency: INR
      - title: PROCESSING_FEE
        price:
          value: '1800'
          currency: INR
      - title: OTHER_UPFRONT_CHARGES
        price:
          value: '0'
          currency: INR
      - title: INSURANCE_CHARGES
        price:
          value: '500'
          currency: INR
      - title: NET_DISBURSED_AMOUNT
        price:
          value: '197700'
          currency: INR
      - title: OTHER_CHARGES
        price:
          value: '0'
          currency: INR
    ttl: P15D
  fulfillments:
    - customer:
        person:
          name: John Doe
        contact:
          phone: +91-9999999999
          email: john.doe@example.com
      state:
        descriptor:
          code: INITIATED
      type: LOAN_JOURNEY
      id: F1
      tags:
        - display: false
          descriptor:
            name: Checklist
            code: CHECKLISTS
          list:
            - descriptor:
                code: PERSONAL_INFORMATION
                name: Personal Information
              value: COMPLETED
            - descriptor:
                code: CONSENT_APPROVAL
                name: Consent Approval
              value: COMPLETED
            - descriptor:
                code: SET_LOAN_AMOUNT
                name: Set Loan Amount
              value: COMPLETED
            - descriptor:
                code: KYC
                name: Know Your Customer
              value: COMPLETED
            - descriptor:
                code: EMANDATE
                name: Emandate
              value: COMPLETED
            - descriptor:
                code: LOAN_AGREEMENT
                name: Loan Agreement
              value: PENDING
            - descriptor:
                code: ACCOUNT_MONITORING
                name: Account Monitoring
              value: PENDING
  payments:
    - type: ON_FULFILLMENT
      id: LOAN_DISBURSMENT_ID
      status: NOT-PAID
      collected_by: CONSUMER
      params:
        bank_account_number: XXXXXXXX
        bank_code: XXXXXXXX
      time:
        label: LOAN_DISBURSMENT
      tags:
        - descriptor:
            name: Account Details
            code: ACCOUNT_DETAILS
          list:
            - descriptor:
                code: ACCOUNT_TYPE
                name: Account Type
              value: SAVINGS
            - descriptor:
                code: ACCOUNT_HOLDER_NAME
                name: Account Holder Name
              value: John Doe
    - type: POST_FULFILLMENT
      id: INSTALLMENT_ID_PERSONAL_LOAN
      params:
        amount: '46360'
        currency: INR
      status: NOT-PAID
      time:
        label: INSTALLMENT
        range:
          start: '2025-06-01T00:00:00.000Z'
          end: '2025-06-30T23:59:59.999Z'
      tags:
        - display: false
          descriptor:
            name: Emi Breakup
            code: BREAKUP
          list:
            - descriptor:
                code: PRINCIPAL_AMOUNT
                name: Principal
                short_desc: Loan Principal
              value: '46000'
            - descriptor:
                code: INTEREST_AMOUNT
                name: Interest
                short_desc: Interest Amount
              value: '360'
    - type: POST_FULFILLMENT
      id: INSTALLMENT_ID_PERSONAL_LOAN
      params:
        amount: '46360'
        currency: INR
      status: NOT-PAID
      time:
        label: INSTALLMENT
        range:
          start: '2025-07-01T00:00:00.000Z'
          end: '2025-07-31T23:59:59.999Z'
      tags:
        - display: false
          descriptor:
            name: Emi Breakup
            code: BREAKUP
          list:
            - descriptor:
                code: PRINCIPAL_AMOUNT
                name: Principal
                short_desc: Loan Principal
              value: '46000'
            - descriptor:
                code: INTEREST_AMOUNT
                name: Interest
                short_desc: Interest Amount
              value: '360'
    - type: POST_FULFILLMENT
      id: INSTALLMENT_ID_PERSONAL_LOAN
      params:
        amount: '46360'
        currency: INR
      status: NOT-PAID
      time:
        label: INSTALLMENT
        range:
          start: '2025-08-01T23:59:59.999Z'
          end: '2025-08-31T23:59:59.999Z'
      tags:
        - display: false
          descriptor:
            name: Emi Breakup
            code: BREAKUP
          list:
            - descriptor:
                code: PRINCIPAL_AMOUNT
                name: Principal
                short_desc: Loan Principal
              value: '46000'
            - descriptor:
                code: INTEREST_AMOUNT
                name: Interest
                short_desc: Interest Amount
              value: '360'
    - type: POST_FULFILLMENT
      id: INSTALLMENT_ID_PERSONAL_LOAN
      params:
        amount: '46360'
        currency: INR
      status: NOT-PAID
      time:
        label: INSTALLMENT
        range:
          start: '2025-09-01T23:59:59.999Z'
          end: '2025-09-30T00:00:00.000Z'
      tags:
        - display: false
          descriptor:
            name: Emi Breakup
            code: BREAKUP
          list:
            - descriptor:
                code: PRINCIPAL_AMOUNT
                name: Principal
                short_desc: Loan Principal
              value: '46000'
            - descriptor:
                code: INTEREST_AMOUNT
                name: Interest
                short_desc: Interest Amount
              value: '360'
    - type: POST_FULFILLMENT
      id: INSTALLMENT_ID_PERSONAL_LOAN
      params:
        amount: '46360'
        currency: INR
      status: NOT-PAID
      time:
        label: INSTALLMENT
        range:
          start: '2025-10-01T00:00:00.000Z'
          end: '2025-10-31T23:59:59.999Z'
      tags:
        - display: false
          descriptor:
            name: Emi Breakup
            code: BREAKUP
          list:
            - descriptor:
                code: PRINCIPAL_AMOUNT
                name: Principal
                short_desc: Loan Principal
              value: '46000'
            - descriptor:
                code: INTEREST_AMOUNT
                name: Interest
                short_desc: Interest Amount
              value: '360'
  cancellation_terms:
    - fulfillment_state:
        descriptor:
          code: SANCTIONED
      cancellation_fee:
        percentage: 3%
    - external_ref:
        mimetype: text/html
        url: 'https://bpp.credit.becknprotocol.org/tnc.html'
    - fulfillment_state:
        descriptor:
          code: DISBURSED
      cancellation_fee:
        percentage: 5%
  tags:
    - display: false
      descriptor:
        name: BPP Terms of Engagement
        code: BPP_TERMS
      list:
        - descriptor:
            code: STATIC_TERMS
          value: >-
            https://bpp.credit.becknprotocol.org/personal-banking/loans/personal-loan
        - descriptor:
            code: OFFLINE_CONTRACT
          value: 'true'
