save-data:
  provider_id: "$.message.catalog.providers[0].id"
  selected_provider: "$.message.catalog.providers[0]"
  item_id: "$.message.catalog.providers[0].items[0].id"
  bpp_id: "$.context.bpp_id"
  bpp_uri: "$.context.bpp_uri"
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  items: "$.message.catalog.providers[*].items[*]"
  product_details_form: "$..form.url"
