intent:
  category:
    descriptor:
      code: "PURCHASE_FINANCE"
  provider:
    id: "PROVIDER_ID"
    items:
      - id: "ITEM_ID_ELECTRONICS"
        xinput:
          form:
            id: "F01"
          form_response:
            status: "SUCCESS"
            submission_id: "F01_SUBMISSION_ID"
  payment:
    collected_by: "BPP"
    tags:
      - descriptor:
          code: "BAP_TERMS"
          name: "BAP Terms of Engagement"
        display: false
        list:
          - descriptor:
              code: "BUYER_FINDER_FEES_TYPE"
            value: "percent-annualized"
          - descriptor:
              code: "BUYER_FINDER_FEES_PERCENTAGE"
            value: "1"
          - descriptor:
              code: "DELAY_INTEREST"
            value: "2.5"
          - descriptor:
              code: "STATIC_TERMS"
            value: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
          - descriptor:
              code: "OFFLINE_CONTRACT"
            value: "true"
