save-data:
  transaction_id: $.context.transaction_id
  message_id: $.context.message_id
  billing: $.message.order.billing
  selected_items: $.message.order.items
  item: $.message.order.items[0]
  selected_fulfillments: $.message.order.fulfillments
  selected_provider: $.message.order.provider
