save-data:
  message_id: "$.context.message_id"
  selected_item_ids: "$.message.order.items[*].id"
  selected_items: "$.message.order.items[*]"
  selected_fulfillments: "$.message.order.fulfilments[*]"
  buyer_side_fulfillment_ids: "$.message.order.fulfillments[*]"
  selected_fulfillment_ids: "$.message.order.fulfillments[*].id"
  select_city_code: "$.context.location.city.code"
