save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  kyc_verification_status: "$..form.url"
  items: "$.message.order.items[*]"
  provider_id: "$.message.order.provider.id"
  item: "$.message.order.items[0]"
  selected_provider: "$.message.order.provider"
  consent_handler: "$.message.order.items[0].tags[0].list[0].value"
  form_id: "$.message.order.items[0].xinput.form.id"
