message:
  order:
    items:
      - id: "I8"
        descriptor:
          name: "Weekly Pass"
          code: "PASS"
          images:
            - url: "https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png"
              size_type: "xs"
        fulfillment_ids:
          - "F1"
        price:
          currency: "INR"
          value: "100"
        quantity:
          selected:
            count: 1
        time:
          label: "Validity"
          duration: "P7D"
          timestamp: "2021-03-23T10:00:40.065Z"
          range:
            start: "2021-03-23T10:00:40.065Z"
            end: "2021-03-29T17:00:40.065Z"
    provider:
      id: "P1"
      descriptor:
        name: "Delhi Transport Corporation"
        images:
          - url: "https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png"
            size_type: "xs"
    fulfillments:
      - id: "F1"
        type: "PASS"
        customer:
          person:
            creds:
              - type: "PAN"
                id: "YKPYS1412V"
        stops:
          - type: "START"
            location:
              descriptor:
                code: "std:011"
              gps: "28.666576, 77.233332"
            id: "1"
        vehicle:
          category: "BUS"
          variant: "AC"
    quote:
      price:
        value: "100"
        currency: "INR"
      breakup:
        - title: "BASE_FARE"
          item:
            id: "I1"
            price:
              currency: "INR"
              value: "100"
            quantity:
              selected:
                count: 1
          price:
            currency: "INR"
            value: "100"
        - title: "OFFER"
          price:
            currency: "INR"
            value: "0"
        - title: "TOLL"
          price:
            currency: "INR"
            value: "0"
