intent:
  fulfillment:
    stops:
      - location:
          gps: "13.008935, 77.644408"
        type: START
      - location:
          gps: "12.971186, 77.586812"
        type: END
  payment:
    collected_by: BAP
    tags:
      - descriptor:
          code: BUYER_FINDER_FEES
        display: false
        list:
          - descriptor:
              code: BUYER_FINDER_FEES_PERCENTAGE
            value: "1"
      - descriptor:
          code: SETTLEMENT_TERMS
        display: false
        list:
          - descriptor:
              code: DELAY_INTEREST
            value: "5"
          - descriptor:
              code: STATIC_TERMS
            value: https://example-test-bap.com/static-terms.txt
