save-data:
  transaction_id: $.context.transaction_id
  message_id: $.context.message_id
  order: $.message.order
  item: $.message.order.items[0]
  payments: $.message.order.payments
  kyc_form_verification_status: $..form.url
  form_id: "$..form.id"