catalog:
  descriptor:
    name: ICICI Bank
  providers:
    - id: PROVIDER_ID
      descriptor:
        images:
          - url: >-
              https://www.icicibank.com/content/dam/icicibank/india/assets/images/header/logo.png
            size_type: sm
        name: ICICI Bank
        short_desc: ICICI Bank Ltd
        long_desc: 'ICICI Bank Ltd, India.'
      items:
        - id: ITEM_ID_LOAN_2
          descriptor:
            code: LOAN
            name: Invoice Based Loan with AA
          category_ids:
            - '101112'
            - '101212'
          fulfillment_ids:
            - F4_AA
          matched: true
          recommended: true
        - id: CHILD_ITEM_ID_LOAN_1
          parent_item_id: ITEM_ID_LOAN_2
          descriptor:
            code: LOAN
            name: Invoice Based Loan with AA
          category_ids:
            - '101112'
            - '101212'
          fulfillment_ids:
            - F4_AA
          price:
            currency: INR
            value: '441800'
          matched: true
          recommended: true
          tags:
            - descriptor:
                code: LOAN_INFO
                name: Information
              list:
                - descriptor:
                    code: INTEREST_RATE
                    name: Interest Rate
                    short_desc: Loans starting from 12% (p.a)
                  value: 12 %
                - descriptor:
                    code: TERM
                    name: Loan Term
                    short_desc: Loans Duration 5 months
                  value: P5M
                - descriptor:
                    code: INTEREST_RATE_TYPE
                    name: Interest rate type
                    short_desc: Fixed Interest type
                  value: FIXED
                - descriptor:
                    code: APPLICATION_FEE
                    name: Application Fees
                    short_desc: Application Fees
                  value: 1000 INR
                - descriptor:
                    code: FORECLOSURE_FEE
                    name: Foreclosure Penalty
                    short_desc: Loan Foreclosure Penalty
                  value: 0.5 %
                - descriptor:
                    code: INTEREST_RATE_CONVERSION_CHARGE
                    name: interest rate conversion charges
                    short_desc: Interest rate conversion charges
                  value: 1000 INR
                - descriptor:
                    code: DELAY_PENALTY_FEE
                    name: Delayed payments penalty
                    short_desc: Delayed payments penalty
                  value: 5 %
                - descriptor:
                    code: OTHER_PENALTY_FEE
                    name: Other Penal Charges
                    short_desc: Other Penal Charges
                  value: 1 %
                - descriptor:
                    code: ANNUAL_PERCENTAGE_RATE
                    name: Annual Percentage Rate
                    short_desc: >-
                      Effective annualized interest rate in percentage computed
                      on net disbursed amount using IRR approach and reducing
                      balance method
                  value: 5 %
                - descriptor:
                    code: REPAYMENT_FREQUENCY
                    name: Repayment Frequency
                    short_desc: Repayment Frequency by borrower
                  value: P1M
                - descriptor:
                    code: NUMBER_OF_INSTALLMENTS
                    name: Number of installments of repayment
                    short_desc: >-
                      Number of installments borrower has to make to payback the
                      loan
                  value: '45'
                - descriptor:
                    code: TNC_LINK
                    name: Terms & Conditions
                    short_desc: Terms and Conditions
                  value: 'https://icicibank.com/loan/tnc.html'
                - descriptor:
                    code: COOL_OFF_PERIOD
                    name: cool off period
                    short_desc: >-
                      Cooling off/look-up period during which borrower shall not
                      be charged any penalty
                  value: P30D
                - descriptor:
                    code: INSTALLMENT_AMOUNT
                    name: Installment amount
                    short_desc: Each installment amount of repayment
                  value: 46360 INR
                - descriptor:
                    code: KFS_LINK
                    name: Key Facts Statement Link
                    short_desc: >-
                      A link provided by the BPP points to a Key Fact Statement
                      (KFS) document related to a loan. When accessed, the
                      document is returned in text/html format, with the loan
                      details organized in a standard HTML table. This format
                      makes it easy for the buyer's app to read and reformat the
                      information as needed. For more details, refer to the
                      \"KFS_LINK format\" document in the \"feature-ui\"
                      section.
                  value: 'https://icicibank.com/loan/kfs-terms'
            - descriptor:
                code: LOAN_OFFER
                name: Loan Offer
              list:
                - descriptor:
                    code: PRINCIPAL_AMOUNT
                    name: Principal Amount
                    short_desc: Loan Principal
                  value: 400000 INR
                - descriptor:
                    code: INTEREST_AMOUNT
                    name: Interest Amount
                    short_desc: Interest Principal
                  value: '30000'
                - descriptor:
                    code: PROCESSING_FEE
                    name: Processing fee
                    short_desc: Processing fee
                  value: '1800'
                - descriptor:
                    code: OTHER_UPFRONT_CHARGES
                    name: Other upfront charges
                    short_desc: Other upfront charges
                  value: '0'
                - descriptor:
                    code: INSURANCE_CHARGES
                    name: Insurance Charges
                    short_desc: Insurance Charges
                  value: '500'
                - descriptor:
                    code: NET_DISBURSED_AMOUNT
                    name: net disbursed amount
                    short_desc: net disbursed amount
                  value: 397700 INR
                - descriptor:
                    code: OTHER_CHARGES
                    name: other charges
                    short_desc: other charges
                  value: '0'
                - descriptor:
                    code: OFFER_VALIDITY
                    name: Offer validity
                    short_desc: Describes the offer validity
                  value: P15D
                - descriptor:
                    code: INVOICE_NUMBER
                    name: Invoice Number
                    short_desc: Describes the Invoice Number
                  value: INV-24-04-009
      fulfillments:
        - id: F4_AA
          type: LOAN_JOURNEY
          tags:
            - display: false
              descriptor:
                name: Checklist
                code: CHECKLISTS
              list:
                - descriptor:
                    code: ORGANIZATION_INFORMATION
                    name: Organization Information
                  value: COMPLETED
                - descriptor:
                    code: CONSENT_APPROVAL
                    name: Consent Approval
                  value: COMPLETED
                - descriptor:
                    code: SET_LOAN_AMOUNT
                    name: Set Loan Amount
                  value: PENDING
                - descriptor:
                    code: INDIVIDUAL_KYC
                    name: Individual KYC
                  value: PENDING
                - descriptor:
                    code: ENTITY_KYC
                    name: Entity KYC
                  value: PENDING
                - descriptor:
                    code: EMANDATE
                    name: Emandate
                  value: PENDING
                - descriptor:
                    code: LOAN_AGREEMENT
                    name: Loan Agreement
                  value: PENDING
                - descriptor:
                    code: ACCOUNT_MONITORING
                    name: Account Monitoring
                  value: PENDING
      payments:
        - type: POST_FULFILLMENT
          id: INSTALLMENT_ID_PERSONAL_LOAN
          status: NOT-PAID
          collected_by: BPP
          time:
            label: INSTALLMENT
        - type: ON_FULFILLMENT
          id: LOAN_DISBURSMENT_ID
          status: NOT-PAID
          collected_by: CONSUMER
          time:
            label: LOAN_DISBURSMENT
      tags:
        - descriptor:
            code: CONTACT_INFO
            name: Contact Info
          list:
            - descriptor:
                code: GRO_NAME
                name: Gro name
              value: ICICI
            - descriptor:
                code: GRO_EMAIL
                name: Gro email
              value: lifeline@iciciprulife.com
            - descriptor:
                code: GRO_CONTACT_NUMBER
                name: Gro contact number
              value: 1860 266 7766
            - descriptor:
                code: CUSTOMER_SUPPORT_LINK
                name: Customer support link
              value: >-
                https://buy.iciciprulife.com/buy/GrievanceRedStep.htm?execution=e1s1
            - descriptor:
                code: CUSTOMER_SUPPORT_CONTACT_NUMBER
                name: Customer support contact number
              value: 1800 INR 1080
            - descriptor:
                code: CUSTOMER_SUPPORT_EMAIL
                name: Customer support email
              value: customer.care@icicibank.com
        - descriptor:
            code: LSP_INFO
            name: Lsp Info
          list:
            - descriptor:
                code: LSP_NAME
                name: Lsp name
              value: ICICI_LSP
            - descriptor:
                code: LSP_EMAIL
                name: Lsp email
              value: lsp@iciciprulife.com
            - descriptor:
                code: LSP_CONTACT_NUMBER
                name: Lsp contact number
              value: 1860 266 7766
            - descriptor:
                code: LSP_ADDRESS
                name: Lsp Address
              value: >-
                One Indiabulls centre, Tower 1, 18th Floor Jupiter mill compound
                841, Senapati Bapat Marg, Elphinstone Road, Mumbai 400013
  tags:
    - display: false
      descriptor:
        name: BPP Terms of Engagement
        code: BPP_TERMS
      list:
        - descriptor:
            code: STATIC_TERMS
          value: >-
            https://bpp.credit.becknprotocol.org/working-capital/loans/working-capital
        - descriptor:
            code: OFFLINE_CONTRACT
          value: 'true'
