order:
  id: LOAN_LEAD_ID_OR_SIMILAR_ORDER_ID
  items:
    - id: CHILD_ITEM_ID_LOAN_1
      xinput:
        form:
          id: F11
        form_response:
          status: SUCCESS
          submission_id: 1b2d7b84-712c-49cf-b0a3-f9c95e8ab5c4
