save-data:
  transaction_id: $.context.transaction_id
  message_id: $.context.message_id
  selected_items: $.message.order.items
  selected_provider: $.message.order.provider
  item: $.message.order.items[0]
