intent:
  category:
    descriptor:
      code: LOAN
  payment:
    collected_by: BPP
  tags:
    - display: false
      descriptor:
        name: BAP Terms of Engagement
        code: BAP_TERMS
      list:
        - descriptor:
            code: STATIC_TERMS
          value: https://bap.credit.becknprotocol.io/working-capital/loans/working-capital
        - descriptor:
            code: OFFLINE_CONTRACT
          value: "true"
