update_target:
  - path: issue.actions
    action: APPENDED
issue:
  id: ISSUE-1
  status: RESOLVED
  level: ISSUE
  created_at: "2023-01-15T10:00:00.469Z"
  updated_at: "2023-01-15T10:00:00.469Z"
  expected_response_time:
    duration: PT2H
  expected_resolution_time:
    duration: P1D
  refs:
    - ref_id: O1
      ref_type: ORDER
    - ref_id: P1
      ref_type: PROVIDER
    - ref_id: F1
      ref_type: FULFILLMENT
    - ref_id: I1
      ref_type: ITEM
      tags:
        - descriptor:
            code: message.order.items
          list:
            - descriptor:
                code: quantity.selected.count
              value: "2"
  actors:
    - id: CUST1
      type: CONSUMER
      info:
        org:
          name: buyerapp.com::ONDC:RET10
        person:
          name: mock-person
        contact:
          phone: "9879879870"
          email: sam@yahoo.com
    - id: NP1
      type: INTERFACING_NP
      info:
        org:
          name: buyerapp.com::ONDC:RET10
        contact:
          phone: "9450394039"
          email: buyerapp@interface.com
        person:
          name: John Doe
    - id: NP2
      type: COUNTERPARTY_NP
      info:
        org:
          name: sellerapp.com::ONDC:RET10
        contact:
          phone: "9450394140"
          email: respondentapp@respond.com
        person:
          name: Jane Doe
    - id: NP2-GRO
      type: COUNTERPARTY_NP_GRO
      info:
        org:
          name: sellerapp.com::ONDC:RET10
        contact:
          phone: "9999994039"
          email: sellerapp@interface.com
        person:
          name: Grievance Officer SNP
  source_id: CUST1
  complainant_id: NP1
  respondent_ids:
    - NP2
  resolver_ids:
    - NP2
  descriptor:
    code: ITM004
    short_desc: Issue with product quality
    long_desc: product quality is not correct. facing issues while using the product
    additional_desc:
      url: https://buyerapp.com/additonal-details/desc.txt
      content_type: text/plain
    images:
      - url: http://buyerapp.com/addtional-details/img1.png
        size_type: xs
      - url: http://buyerapp.com/addtional-details/img2.png
        size_type: xs
  last_action_id: A11
  actions:
    - id: A1
      descriptor:
        code: OPEN
        short_desc: Complaint created
      updated_at: "2023-01-15T10:00:00.469Z"
      action_by: NP1
      actor_details:
        name: mock-person
    - id: A2
      descriptor:
        code: PROCESSING
        short_desc: Complaint created
      updated_at: "2023-01-15T10:00:00.469Z"
      action_by: NP2
      actor_details:
        name: mock-person
    - id: A3
      descriptor:
        code: INFO_REQUESTED
        name: INFO01
        short_desc: Please provide product image
      updated_at: 2023-01-15T10:00:00.489Z
      action_by: NP2
      actor_details:
        name: mock-person
    - id: A4
      ref_id: A3
      descriptor:
        code: INFO_PROVIDED
        short_desc: Responded with images
        images:
          - url: http://buyerapp.com/addtional-details/img1.png
            size_type: xs
          - url: http://buyerapp.com/addtional-details/img2.png
            size_type: xs
      updated_at: "2023-01-15T10:00:00.469Z"
      action_by: NP1
      actor_details:
        name: mock-person
    - id: A5
      descriptor:
        code: PROCESSING
        short_desc: Complaint created
      updated_at: "2023-01-15T10:00:00.469Z"
      action_by: NP1
      actor_details:
        name: mock-person
    - id: A6
      ref_id: R_PARENT
      ref_type: RESOLUTIONS
      descriptor:
        code: RESOLUTION_PROPOSED
        short_desc: Resolution is proposed
      updated_at: "2023-01-15T10:00:00.469Z"
      action_by: NP2
      actor_details:
        name: mock-person
    - id: A7
      ref_id: R2
      ref_type: RESOLUTIONS
      descriptor:
        code: RESOLUTION_ACCEPTED
        short_desc: Resolution is accepted
      updated_at: "2023-01-15T10:00:00.469Z"
      action_by: NP1
      actor_details:
        name: mock-person
    - id: A8
      ref_id: R2
      ref_type: RESOLUTIONS
      descriptor:
        code: RESOLVED
        name: REPLACEMENT
        short_desc: Providing replacement
      updated_at: "2023-01-15T10:00:00.469Z"
      action_by: NP2
      actor_details:
        name: mock-person

  resolutions:
    - id: R_PARENT
      descriptor:
        code: PARENT
        short_desc: PROVIDING RESOLUTION OPTIONS. PLEASE SELECT ONE
      updated_at: "2024-08-14T09:57:58.841Z"
      proposed_by: NP2
    - id: R1
      ref_id: R_PARENT
      ref_type: PARENT
      descriptor:
        code: REFUND
        short_desc: Providing refund for the item
      updated_at: "2024-08-14T09:57:58.841Z"
      proposed_by: NP2
      tags:
        - descriptor:
            code: RESOLUTION_DETAILS
          list:
            - descriptor:
                code: ITEM
              value: I1
            - descriptor:
                code: REFUND_AMOUNT
              value: "200"
    - id: R2
      ref_id: R_PARENT
      ref_type: PARENT
      descriptor:
        code: REPLACEMENT
        short_desc: Providing replacement of the item
      updated_at: "2024-08-14T09:57:58.841Z"
      proposed_by: NP2
      tags:
        - descriptor:
            code: RESOLUTION_DETAILS
          list:
            - descriptor:
                code: ITEM
              value: I1
