catalog:
  descriptor:
    name: ICICI Bank
  providers:
    - id: PROVIDER_ID
      descriptor:
        images:
          - url: >-
              https://www.icicibank.com/content/dam/icicibank/india/assets/images/header/logo.png
            size_type: sm
        name: ICICI Bank
        short_desc: ICICI Bank Ltd
        long_desc: 'ICICI Bank Ltd, India.'
      items:
        - id: ITEM_ID_LOAN_2
          descriptor:
            code: LOAN
            name: Invoice Based Loan with AA
          category_ids:
            - '101112'
            - '101212'
          fulfillment_ids:
            - F4_AA
          matched: true
          recommended: true
          xinput:
            head:
              descriptor:
                name: Consent Approval
                code: CONSENT_APPROVAL
              headings:
                - ORGANIZATION_INFORMATION
                - CONSENT_APPROVAL
            form:
              id: F01
              mime_type: none
              data:
                consent_handler: d4cabdca-f621-43f7-9c8b-b5331d329e09
              resubmit: false
              multiple_sumbissions: false
            required: true
      fulfillments:
        - id: F4_AA
          type: LOAN_JOURNEY
          tags:
            - display: false
              descriptor:
                name: Checklist
                code: CHECKLISTS
              list:
                - descriptor:
                    code: ORGANIZATION_INFORMATION
                    name: Organization Information
                  value: COMPLETED
                - descriptor:
                    code: CONSENT_APPROVAL
                    name: Consent Approval
                  value: PENDING
                - descriptor:
                    code: SET_LOAN_AMOUNT
                    name: Set Loan Amount
                  value: PENDING
                - descriptor:
                    code: INDIVIDUAL_KYC
                    name: Individual KYC
                  value: PENDING
                - descriptor:
                    code: ENTITY_KYC
                    name: Entity KYC
                  value: PENDING
                - descriptor:
                    code: EMANDATE
                    name: Emandate
                  value: PENDING
                - descriptor:
                    code: LOAN_AGREEMENT
                    name: Loan Agreement
                  value: PENDING
                - descriptor:
                    code: ACCOUNT_MONITORING
                    name: Account Monitoring
                  value: PENDING
      payments:
        - type: POST_FULFILLMENT
          id: INSTALLMENT_ID_LOAN
          status: NOT-PAID
          collected_by: BPP
          time:
            label: INSTALLMENT
        - type: ON_FULFILLMENT
          id: LOAN_DISBURSMENT_ID
          status: NOT-PAID
          collected_by: CONSUMER
          time:
            label: LOAN_DISBURSMENT
      tags:
        - descriptor:
            code: CONTACT_INFO
            name: Contact Info
          list:
            - descriptor:
                code: GRO_NAME
                name: Gro name
              value: ICICI
            - descriptor:
                code: GRO_EMAIL
                name: Gro email
              value: lifeline@iciciprulife.com
            - descriptor:
                code: GRO_CONTACT_NUMBER
                name: Gro contact number
              value: 1860 266 7766
            - descriptor:
                code: CUSTOMER_SUPPORT_LINK
                name: Customer support link
              value: >-
                https://buy.iciciprulife.com/buy/GrievanceRedStep.htm?execution=e1s1
            - descriptor:
                code: CUSTOMER_SUPPORT_CONTACT_NUMBER
                name: Customer support contact number
              value: 1800 INR 1080
            - descriptor:
                code: CUSTOMER_SUPPORT_EMAIL
                name: Customer support email
              value: customer.care@icicibank.com
        - descriptor:
            code: LSP_INFO
            name: Lsp Info
          list:
            - descriptor:
                code: LSP_NAME
                name: Lsp name
              value: ICICI_LSP
            - descriptor:
                code: LSP_EMAIL
                name: Lsp email
              value: lsp@iciciprulife.com
            - descriptor:
                code: LSP_CONTACT_NUMBER
                name: Lsp contact number
              value: 1860 266 7766
            - descriptor:
                code: LSP_ADDRESS
                name: Lsp Address
              value: >-
                One Indiabulls centre, Tower 1, 18th Floor Jupiter mill compound
                841, Senapati Bapat Marg, Elphinstone Road, Mumbai 400013
  tags:
    - display: false
      descriptor:
        name: BPP Terms of Engagement
        code: BPP_TERMS
      list:
        - descriptor:
            code: STATIC_TERMS
          value: >-
            https://bpp.credit.becknprotocol.org/working-capital/loans/working-capital
        - descriptor:
            code: OFFLINE_CONTRACT
          value: 'true'
