save-data:
  transaction_id: $.context.transaction_id
  message_id: $.context.message_id
  order_id: $.message.order.id
  selected_provider: $.message.order.provider
  item: $.message.order.items[0]
  payments: $.message.order.payments
