intent:
  provider:
    id: PROVIDER_ID
    items:
      - id: ITEM_ID_PERSONAL_LOAN_1
        xinput:
          form:
            id: F01
            data:
              panName:
                value: Mary Jane Watson
              personalemail:
                value: example@gmail.com
              officialemail:
                value: example@gmail.com
              dob:
                value: 17/12/2001
              gender:
                value: Male
              pan:
                value: RKNPS5743R
              contactNumber:
                value: '+919123456789'
              employmentType: ' value: Salaried'
              income:
                value: '213414'
              companyName:
                value: Test 1
              udyamNumber:
                value: UDYAM-XX-00-0000000
              addressL1:
                value: 'Flat No. 5, ABC Apartments'
              addressL2:
                value: 'Flat No. 5, ABC Apartments'
              city:
                value: Mumbai
              state:
                value: Maharashtra
              pincode:
                value: '110001'
              bureauConsent:
                value: 'true'
              aa_id:
                value: 9999999999@finvu
              endUse:
                value: Purchase of Consumer Durables
  payment:
    collected_by: BPP
  tags:
    - display: false
      descriptor:
        name: BAP Terms of Engagement
        code: BAP_TERMS
      list:
        - descriptor:
            code: STATIC_TERMS
          value: >-
            https://bap.credit.becknprotocol.io/working-capital/loans/working-capital
        - descriptor:
            code: OFFLINE_CONTRACT
          value: 'true'
