issue:
  id: ISSUE-1
  status: OPEN
  level: ISSUE
  created_at: "2023-01-15T10:00:00.469Z"
  updated_at: "2023-01-15T10:00:00.469Z"
  expected_response_time:
    duration: PT2H
  expected_resolution_time:
    duration: P1D
  refs:
    - ref_id: O1
      ref_type: ORDER
    - ref_id: P1
      ref_type: PROVIDER
    - ref_id: F1
      ref_type: FULFILLMENT
    - ref_id: I1
      ref_type: ITEM
      tags:
        - descriptor:
            code: message.order.items
          list:
            - descriptor:
                code: quantity.selected.count
              value: "2"
  actors:
    - id: CUST1
      type: CONSUMER
      info:
        org:
          name: "buyerapp.com::ONDC:RET10"
        person:
          name: mock-person
        contact:
          phone: "9879879870"
          email: sam@yahoo.com
    - id: NP1
      type: INTERFACING_NP
      info:
        org:
          name: "buyerapp.com::ONDC:RET10"
        contact:
          phone: "9450394039"
          email: buyerapp@interface.com
        person:
          name: John Doe
  source_id: CUST1
  complainant_id: NP1
  descriptor:
    code: PMT002
    short_desc: The actual payout made is less than expected
    long_desc: The actual payout made is less than expected
    additional_desc:
      url: "https://buyerapp.com/additonal-details/desc.txt"
      content_type: text/plain
    images:
      - url: "https://transitsolutions.in/logos/logo.icon"
        size_type: xs
    media:
      - url: "https://transitsolutions.in/logos/logo.icon"
  last_action_id: A1
  actions:
    - id: A1
      descriptor:
        code: OPEN
        short_desc: Complaint created
      updated_at: "2023-01-15T10:00:00.469Z"
      action_by: NP1
      actor_details:
        name: mock-person
