message:
  order:
    items:
      - id: "I1"
        quantity:
          selected:
            count: 1
    fulfillments:
      - id: "F1"
        type: "PASS"
        customer:
          person:
            creds:
              - type: "PAN"
                id: "YKPYS1412V"
    provider:
      id: "P1"
