save-data:
  message_id: "$.context.message_id"
  selected_item_ids: "$.message.order.items[*].id"
  selected_items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  buyer_side_fulfillment_ids: "$.message.order.fulfillments[*]"
  pan_id: "$.message.order.fulfillments[*].customer.person.creds[?(@.type=='PAN')].id"

