save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  selected_provider: "$.message.order.provider"
  selected_items: "$.message.order.items[*]"
  selected_fulfillments: "$.message.order.fulfillments[*]"
  quote: "$.message.quote" 
  Ekyc_details_verification_status: "$..form.url"
  form_id: "$..form.id"
  item: "$.message.order.items[1]"
