save-data:
  status: "$.message.order.status"
  fulfillments: "$.message.order.fulfillments[*]"
  quote: "$.message.order.quote"
  items: "$.message.order.items[*]"
  payments: "$.message.order.payments[*]"
  newQuote: "$.message.order.quote.price.value"
  on_update_tags: "$.message.order.tags"
